### ISSUE TITLE
Adresszuweisung defekt?

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#102]
Was habe ich getan?
1. Pia hat sich selbst Registriert 
2. Pia hat Sören eingegeben in der Mitgliederliste
=> Sörens Adresse erscheint unter seinem Namen und unter Pias
3. Pia hat Devin eingegeben
=> Devins Adresse liegt unter Pias und Devins Namen

Vermutung?
Die Person, die eine Adresse eingibt hat diese Adresse immer auch als eigene?

![whatsapp image 2018-03-22 at 11 36 39](https://user-images.githubusercontent.com/25246294/37765975-f27dff8a-2dc5-11e8-8512-8d4e88c9b3ba.jpeg)

![whatsapp image 2018-03-22 at 11 37 32](https://user-images.githubusercontent.com/25246294/37766012-08fa0ccc-2dc6-11e8-993b-4660befd2687.jpeg)

**Comment by lehoffma** [comment]
Sollte in [diesem Commit](https://github.com/lehoffma/memo/commit/c78f357bdac79a6f9c76656e2156181b98140f5c) gefixt worden sein.

**Comment by sinnloserName4** [comment]
![image](https://user-images.githubusercontent.com/6012426/37908618-0d1ae8a8-3109-11e8-8d2f-6205acf7d715.png)
![image](https://user-images.githubusercontent.com/6012426/37908628-12d0ddc0-3109-11e8-9d24-94ff8aaefc11.png)

ist leider immernoch so

**Comment by lehoffma** [comment]
Bei mir isses leider immer noch nich so 😅 passiert das immer oder nur manchmal?

**Comment by sinnloserName4** [comment]
jetzt tritt es nicht auf. Das war gerade, als meine Datenbank nicht mehr wollte. Scheint sich ja aber aufs Frontend zu beschränken, gibt auch keine extra API Calls dafür
