### ISSUE TITLE
Waren kaufen auch bei 0 Euro

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#105]
Wenn eine Ware im Wert von 0 Euro im Warenkorb ist kann sie nicht gekauft werden. 

![unbenannt](https://user-images.githubusercontent.com/25246294/37766778-3e7db464-2dc8-11e8-9e90-e398c7702cad.png)

**Comment by lehoffma** [comment]
Sollte jetzt funktionieren (wurde in [diesem Commit](https://github.com/lehoffma/memo/commit/c78f357bdac79a6f9c76656e2156181b98140f5c) gefixt).
