### ISSUE TITLE
Stock Aufruf mit ID = null  404

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#107]
Wenn ich im mobilen Modus auf "Merchandise" klicke, versucht er Stocks der ID "null" zu suchen, die es natürlich nicht gibt. Daher gibt es bei mir immer 4 mal 404 bei dem GET. Siehe Bild

![unbenannt](https://user-images.githubusercontent.com/25246294/37877238-281c1700-3058-11e8-8dab-e83b6d6c2f64.png)

**Comment by lehoffma** [comment]
Das is so gewollt. Die ID in dem request is die ID des stock items, hier wird aber nich ein bestimmtes stock event gesucht,  sondern alle stock items vom event mit der ID=2. Dass die id=null extra im request drin steht is zwar unnötig, macht aber keinen Unterschied. Und der 404 kommt automatisch wenn die stock Liste des merch's leer is. Is auch nich unbedingt optimal, führt aber eigentlich nicht zu Fehlern. Wenn du dem merch Objekt bestand hinzufügst, sind das auch keine 404s mehr

**Comment by PiaLamprecht** [comment]
ich hab in dem fall 3 Merch-Elemente, die mir dort alle nicht angezeigt wurden, daher habe ich mich gewundert, dass er 404 zeigt es muss ja elemente geben :(

**Comment by lehoffma** [comment]
Dass das n 404 gibt ist ja nicht schlimm in dem Fall. Das heißt erstmal nur, dass er zu diesen Merch Objekten keine Stock-Items gefunden hat. 
Das sollte aber zukünftig nicht mehr passieren, weil man jetzt immer mindestens eine Größe/Farbe-Kombination angeben muss beim Erstellen des Merch-Objektes. Vorher erstellte Artikel können aber natürlich immer noch kaputt sein.
