### ISSUE TITLE
Pflichfeld Farbe/Größe eines Merch-Artikels

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#108]
Die Fabe bzw. Größe eines Merch-Artikels muss ein PFlichtfeld sein. Auch wenn man nur OneSize eingibt sonst können die Artikel nicht gekauft werden. (Warenkorb wird nicht grün)

![unbenannt1](https://user-images.githubusercontent.com/25246294/37877342-1733dcfa-305a-11e8-80d6-2899524303ba.png)

**Comment by lehoffma** [comment]
Das Stock-Formular hab ich ehrlich gesagt auch einfach vergessen beim refactoren. Hab ich jetzt mal geändert, man muss jetzt immer mindestens eine Farbe und eine Größe angeben.
