### ISSUE TITLE
Menü an der Seite ist machmal nicht da

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#110]
Manchmal ist das Seitenmenü einfach nicht da. Hab einfach ganz normal den Tomcat und npm gestartet und dann auf den Handymodus geschaltet. Auch nachdem ich aktuallisiert habe ist es nicht erschienen. 

![unbenannt](https://user-images.githubusercontent.com/25246294/37878489-6664b1b8-306a-11e8-8990-441a06f3738e.png)

**Comment by PiaLamprecht** [comment]
wenn ich den localStorage cleare geht es natürlich wieder

**Comment by lehoffma** [comment]
Weird, den Fehler hatte ich nur manchmal weil die Datenbank zu langsam is.
Im moment wird da darauf gewartet, dass der automatische login request abgeschlossen is (oder dass der refresh token null is), also das is am anfang immer kurz leer. Ich werd das mal so umbauen, dass zumindest die sachen angezeigt werden, die man ausgeloggt sehen kann.
Aber eigentlich hätte er es anzeigen müssen, der Login request is ja nich gefailt oder so. Schau ich mir auf jeden fall mal an.

**Comment by lehoffma** [comment]
Konnte ich nicht wirklich reproduzieren, aber die ausgeloggte Sicht als Default-Wert ist implementiert. Öffne einfach hier wieder wenns noch mal auftreten sollte.
