### ISSUE TITLE
Merch-Seite schließt nicht nach Erstellung

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#112]
Wenn ein Merch-Artikel erstellt wird schließt sich die Seite nicht, daher erstellt man öfters mal mehrere

**Comment by lehoffma** [comment]
Also du meinst,  dass man nich weiter geleitet wird oder wie?

**Comment by PiaLamprecht** [comment]
ja genau man versteht nicht dass man es erstellt hat sozusagen xD

**Comment by PiaLamprecht** [comment]
funktioniert
