### ISSUE TITLE
Telefonfelder sollten keine Pflichtfelder sein

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#116]
Nur eine Telefonnummer sollte verpflichtend sein.

![image](https://user-images.githubusercontent.com/6012426/37908139-8c6f5424-3107-11e8-8577-0af60c387445.png)

Keine der beiden anzugeben wäre im Prinzip auch okay, aber ich hab z.B. gar keine zwei nummern 👯‍♂️

**Comment by lehoffma** [comment]
Hatte irgendwie im Kopf, dass das auch in der DB verpflichtend war. Habs mal optional gemacht.
