### ISSUE TITLE
Tour Ordnung nach Datum 

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#122]
Ich finde Touren sollten nach Tagen geordnet werden. 
Also die als nächstes stattfindende Tour sollte nach vorne gestelllt werden. 
Was denkt ihr?

![image](https://user-images.githubusercontent.com/25246294/37961472-b09395ac-31b8-11e8-95e5-4ec4db98e698.png)

**Comment by lehoffma** [comment]
Ergibt Sinn find ich. Is jetzt auch so implementiert :)
