### ISSUE TITLE
Errechnung der Meilenliste

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#125]
Die Meilentabelle sollte sich aus den Meilen der jeweils teilgenommenen Touren errechnen. 

Ist das Filtern jetzt relevant?

**Comment by lehoffma** [comment]
Ist implementiert, auch mit Filtern. Das Filtern kann man im Frontend aber nur bei der Meilentabelle durchführen, auf dem Profil werden erstmal einfach die all-time meilen angezeigt.
