### ISSUE TITLE
Impressum befüllen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#127]
- [x] Impressum muss noch gefüllt werden
- [x] Haftungsausschluss einfügen (http://www.haftungsausschluss.org/haftungsausschluss/)

**Comment by sinnloserName4** [comment]
[impressum.pdf](https://github.com/lehoffma/memo/files/1883363/impressum.pdf)
[datenschutzerklaerung.pdf](https://github.com/lehoffma/memo/files/1883364/datenschutzerklaerung.pdf)

**Comment by lehoffma** [comment]
Hab die beiden Texte aus den PDFs in @sinnloserName4's Post eingefügt.
