### ISSUE TITLE
"Tour beendet"-Seite hinzufügen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#129]
Nachdem eine Tour beendet wurde, sollte das Gruppenbild hochgeladen und die Meilen verteilt werden.

**Comment by lehoffma** [comment]
Meilen werden ja jetzt sowieso dynamisch berechnet, Gruppenbild hochladen + für Bericht verantwortliche Nutzer festlegen ist jetzt implementiert.
