### ISSUE TITLE
Adminkonto am Anfang erstellen

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#131]
Es sollte immer ein Adminkonto geben. Dann können auch die Demo Features zu den Permissions raus

- [x] Adminkonto bei jeder DB-Erstellung miterstellen

- [x] Demo-Features entfernen

**Comment by lehoffma** [comment]
Habs jetzt erstmal so implementiert, dass der admin beim ersten api Aufruf direkt erstellt wird, also beim verfügbare Emails checken oder beim einloggen. Ist aber gerade nur sehr wenig getestet, also guckt da mal am besten noch mal drüber. Achso die Demo clubrole is dementsprechend  auch raus.
