### ISSUE TITLE
Nach Registrierung wird das Geschlecht (etc.) falsch gesetzt

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#133]
Wenn ich mich registriere wird das Geschlecht auf "Sonstiges" gesetzt und nicht wie ich angegeben hab auf weiblich. Wenn ich Dauerkarte auswähle wird dies ebenfalls nicht gesetzt.

Hier bei beiden Beispielen zu sehen:

![unbenannt](https://user-images.githubusercontent.com/25246294/38356779-f7a21176-38c0-11e8-9fc2-369dca84e2bc.png)

Bei einer Anmeldung per Admin passiert das nicht.

**Comment by lehoffma** [comment]
Eigentlich komisch, dass das vorher gar nich aufgefallen is 😄 ist gefixt!
