### ISSUE TITLE
Das Löschen einer Adresse im eigenen Account nicht möglich

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#136]
Wenn man über "Dein Account" versucht die eigene Adresse zu löschen und eine neue einzugeben entsteht ein Fehler. 

![image](https://user-images.githubusercontent.com/25246294/38357407-d47325ee-38c2-11e8-9893-a431dc16deb8.png)

**Comment by lehoffma** [comment]
Ist gefixt!
