### ISSUE TITLE
User Status wird nicht gespeichert

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#137]
Ich habe mich als Admin angemeldet um Pia Lamprecht (Gast) als Vorstand zu ernennen 🥇 Jedoch wurde die Änderungen anscheinend nicht gespeichert. Als ich mich mit Pia Lamprecht angemeldet habe war sie immer noch Gast. 

Mein Weg: 
hab den User Pia Lamprecht erstellt
Hab mich als Admin angemeldet
Von der Mitgliederliste habe ich Pia Lamprecht ausgewählt und ihren Status auf Vorstand geändert zu Heute. 
Dann hab ich mich als Pia Lamprecht angemeldet. Auf dem Profil stand jedoch nur Gast und ich konnte den Vorstandsbereich nicht sehen.
Es gab keine Fehler.

**Comment by PiaLamprecht** [comment]
Nach neuem aus und einloggen wurde der Status übernommen

**Comment by lehoffma** [comment]
Richtig nerviger Bug. Das lag wohl am Ende daran, dass der EntityManager im Backend pro Thread wiederverwendet wurde. Da dadurch der PUT request dann manchmal anscheinend auf dem einen Thread entgegen genommen und auf dem anderen Thread mit GET abgefragt wurde, kamen dann unterschiedliche Daten raus. Wenn man oft genug aktualisiert hat, kamen auch wieder die richtigen Daten raus, weil dieses Mal dann n anderer Thread dran war. Aber wenn man noch n paar Mal aktualisiert hatte, warens wieder die alten Daten und so weiter..
Als das dann gefixt war, sind die User auf ein mal beim Modifizieren dupliziert statt editiert worden, weil im Servlet `save `und nich `update` aufgerufen wurde. Keine Ahnung, wie das vorher nich schon aufgefallen ist.

Is jetzt auf jeden Fall gefixt 😅
