### ISSUE TITLE
Fehler bei Merch

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#140]
Keine Ahnung, warum ich einen Fehler habe. 
Hab ein Merch-Artikel erstellt:
- 4 Bilder
- hab alle Felder ausgefüllt
- hab jeweils s, m, l in schwarz, weis und grün

![image](https://user-images.githubusercontent.com/25246294/38544626-413292b2-3ca8-11e8-865b-9c245e79cc57.png)

**Comment by PiaLamprecht** [comment]
Nachdem ich einen Pullover gekauft habe, kann ich keinen mehr kaufen. So als hätte ich alle gekauft :(

**Comment by lehoffma** [comment]
Der erste Teil ist gefixt.

> Nachdem ich einen Pullover gekauft habe, kann ich keinen mehr kaufen. So als hätte ich alle gekauft :(

Das sollte eigentlich nicht mit dem ersten Teil zusammenhängen. Bei mir passiert das aber auch nicht, also vielleicht hat der Fix des ersten Teils das auch schon gefixt. Falls es immer noch bei dir auftreten sollte, mach am besten ein separates Issue auf.
