### ISSUE TITLE
Fehler beim Abschließen des Einkaufs (per Überweisung)

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#141]
![image](https://user-images.githubusercontent.com/25246294/38545315-0f7d4dbe-3caa-11e8-88c3-6f183294263c.png)

![image](https://user-images.githubusercontent.com/25246294/38545358-27ba4fb2-3caa-11e8-88cf-dd0ff3ff52e4.png)

**Comment by PiaLamprecht** [comment]
Das gleiche bei Lastschrift

![image](https://user-images.githubusercontent.com/25246294/38545612-b6c888b8-3caa-11e8-857e-be774dd083f1.png)

**Comment by lehoffma** [comment]
Tritt das immer noch auf? (bei mir klappt das nämlich alles soweit)
