### ISSUE TITLE
Profilbild löschen funktioniert nicht

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#142]
Das Profilbild wird nicht gelöscht bzw. geändert. 

Weg:
Profil mit Bild erstellt
Auf eigenes Profil --> Bild gelöscht --> Bild hinzugefügt --> speichern

Altes Bild wird angezeigt. 

![image](https://user-images.githubusercontent.com/25246294/38551195-e01250ba-3cb8-11e8-907c-eb4441d4a2ad.png)

**Comment by lehoffma** [comment]
Kann ich gerade nicht reproduzieren (weder für den Admin noch für einen Gast Account), kannst du schauen ob das bei dir immer noch auftritt?

**Comment by lehoffma** [comment]
Noch mal hier:
Sollte jetzt gefixt sein. Lag wohl daran, dass der Cascade=ALL Wert bei den Images dazu geführt hat, dass in der DB mehr als ein Bild mit dem gleichen Pfad erstellt wurden. Das is an sich schon blöd, aber dann kommt noch dazu, dass nur eins davon den korrekten UserId Wert hatte, die anderen hatten alle null. Und in der Registrierungs-Situation hat er wohl immer genau das falsche Image-Objekt zurückbekommen.
