### ISSUE TITLE
Keine Mail wegen Rollenänderung angekommen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#144]
Pia Sophie Lamprecht (Gast) hat angegeben sie sie Mitglied. Normalerweise müsste der Admin eine Mail bekommen haben, dass er die Rolle ändern soll. Leider ist keine Mail angekommen. Gibt es noch keine Mail?

**Comment by lehoffma** [comment]
Ja, es gibt noch keine Mail bzw. sie ist noch nicht eingebaut.

**Comment by PiaLamprecht** [comment]
gebaut sie ist

**Comment by lehoffma** [comment]
Ist implementiert, konnte es nicht so richtig testen weil ich nich weiß wie ich auf die Mail vom Admin zugreifen kann 😅

**Comment by PiaLamprecht** [comment]
![image](https://user-images.githubusercontent.com/25246294/38734720-ead90226-3f26-11e8-88c8-b74f64eb1bce.png)

läuft
