### ISSUE TITLE
An mehr Touren teilgenommen als gekauft

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#145]
Sehr merkwürdig: 

ich hatte eine Tour im Warenkorb und hab auch nur diese gekauft (siehe E-Mail). Aber in der Liste "Deine Events" sind zwei Touren. 

E-Mail:
![image](https://user-images.githubusercontent.com/25246294/38552309-0ab8181a-3cbc-11e8-9d19-5797085ec1e8.png)

Bestellungen:
![image](https://user-images.githubusercontent.com/25246294/38552322-143b74ae-3cbc-11e8-913c-a982a71a08ae.png)

Teilgenommene Touren: 
![image](https://user-images.githubusercontent.com/25246294/38552272-f1af430c-3cbb-11e8-9a54-18e347084c62.png)

**Comment by sinnloserName4** [comment]
lässt sich nach den änderungen nicht mehr reproduzieren
