### ISSUE TITLE
Tour - Plätze werden nicht weniger 

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#149]
Es waren 12 Plätze und es sind noch 12 Plätze. Obwohl 3 Plätze weg sein müssten. 

![image](https://user-images.githubusercontent.com/25246294/38692820-49251bc8-3e85-11e8-9d50-14a80486e62d.png)

![image](https://user-images.githubusercontent.com/25246294/38692838-575f6b44-3e85-11e8-9360-ffb448f92db2.png)

**Comment by lehoffma** [comment]
Siehe #98.
