### ISSUE TITLE
Vergabe der Meilen als Batch

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#150]
es wär cool wenn man mehrere Leute der Tour auswählen könnte um die Meilen zu vergeben. So muss jede einzelne Person ausgewählt werden ähnlich wie beim löschen

**Comment by sinnloserName4** [comment]
Ich denke wir sollten uns ganz allgemein nochmal gedanken um den Prozess für Touren machen

**Comment by lehoffma** [comment]
Ich glaube damit war die Batchbearbeitung von Participants (also #202) gemeint oder? 
Ich close das issue deshalb erstmal (ist gefixt/sowieso ein duplikat), falls ich es falsch verstanden habe macht es bitte einfach wieder auf (@PiaLamprecht)
