### ISSUE TITLE
vom Login Screen gibt es keinen Weg zurück.

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#152]
Man kommt außer mit der Browser zurück Taste nicht mehr auf den Hauptbildschirm zurück. 
Entweder sollte das Burgermenü zur Vefügung stehen oder zumindest das Meilenwölfe Logo anklickbar sein.
Was denkt ihr?

**Comment by lehoffma** [comment]
Das Meilenwölfe Logo ist jetzt auf allen Fullscreen Seiten (auf denen die Navigation verdeckt ist) anklickbar.
