### ISSUE TITLE
applyForMembership email

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#154]
In dem Text sollte statt info@meilenwoelfe.de eine andere stehen, da diese nur bei mir ankommt und nicht beim vorstand (außerdem gibt es dahin einen haufen spam)

Besser wäre vorstand@meilenwoelfe.de

**Comment by lehoffma** [comment]
Ich hab die Mails doch gar nich gemacht 😅

**Comment by lehoffma** [comment]
Ich hab den Text auch nur von eurer Seite kopiert :D ich änders mal um.
