### ISSUE TITLE
Problem beim User bearbeiten

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#156]
Abbruch einer Bearbeitungsoperation führt nicht zum Rollback.
Nach Abbruch einer Bearbeitung des Users funktioniert der Speicherbutton nicht mehr.

# Was ich gemacht habe
Als Admin habe ich versucht die Rolle eines anderen Users auf "Organisator" zu setzen. Nach klicken auf Speichern wurde sehr lange geladen. Nach etwa 30 Sekunden habe ich auf Abbrechen geklickt. Alles wurde trotzdem gespeichert. Danach wollte ich einen weiteren User bearbeiten, aber der Speichern-Button war immer disabled.

**Comment by lehoffma** [comment]
Den Grund für das lange Laden beim Speichern konnte ich aber zumindest fixen 😄

**Comment by sinnloserName4** [comment]
rollback ist nicht einfach möglich aber Aufwand/Ertrag ist nicht richtig
