### ISSUE TITLE
Foto vom Admin ändern sich, wenn der Mitgliederdaten speichert

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#159]
Ich habe mich als Admin angemeldet um Pia als Vorstand zu bennen.
Als ich sie gespeichert habe ist ihr Profilbild oben angezeigt worden. 

Auf dem Bild bin ich unter mein Profil (bin also Admin). Oben wird aber das Bild des Mitglieds abzeiegt. 

![image](https://user-images.githubusercontent.com/25246294/39087281-102b9038-459f-11e8-8464-6cfa0c7d15e4.png)

**Comment by lehoffma** [comment]
Hast du davor irgendwas noch gemacht? Wenn ich einfach nur einen User bearbeite als Admin, passiert das bei mir nicht.
