### ISSUE TITLE
E-Mail kann keine ü/ö anzeigen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#160]
Die Mail für den Admin zur Rollenänderung kann keine ö und üs anzeigen 

![image](https://user-images.githubusercontent.com/25246294/39088333-08fd290a-45b0-11e8-8c32-3b0f46e9b65f.png)

**Comment by lehoffma** [comment]
Da müssten die Umlaute durch die entsprechenden HTML-Codes  (also z.B. `&ouml;` für ein ö) in den .html-Dateien ausgetauscht werden. Das Fragezeichen unten am Ende beim Meilenwölfe Shop Button sollte ja auch eigentlich ein Pfeil sein, da müsste statt → dann `&rarr;` eingefügt werden.

**Comment by lehoffma** [comment]
Da hast du anscheinend ja schon was im `backend-test` branch gepusht, schieb das mal in `develop` rein. Dann können wir das ja auch auf den Server pushen

**Comment by sinnloserName4** [comment]
sollte schon eine weile gelöst sein
