### ISSUE TITLE
Tour kann nicht erstellt werden --> Adressfehler

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#161]
Ich habe eine Tour erstellt mit drei Adresse (mit Zwischenstopp). Danach trat dieser Fehler auf:

![image](https://user-images.githubusercontent.com/25246294/39088466-df3dc64e-45b2-11e8-9535-a4cf5153421e.png)

**Comment by PiaLamprecht** [comment]
Tritt auch bei Veranstaltungen und nur einer Adresse auf.

**Comment by lehoffma** [comment]
Sollte jetzt gefixt sein. Hab auch noch mal simple Error-Popups für die Unauthorized, 500er, und 503/504er (Server is offline/timeout) Fehler hinzugefügt.
