### ISSUE TITLE
Image POST - Filesize

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#162]
![image](https://user-images.githubusercontent.com/6012426/39088563-91e768b2-45b4-11e8-9bba-4115dde7efd1.png)

Ich habe ein Bild angegeben und die maximale Filegröße von 5MB überschritten (normales Bild vom Smartphone) und bekomme dann einen 500er.

Vorgehen (kurzfristig): große Bilder aussortieren und nicht bei der Präsentation zeigen.

Vorgehen mittelfristig: Kann man technisch die Filesize hochsetzen? Ansonsten zumindest ein vernünftiges Errorhandling

**Comment by lehoffma** [comment]
Die hatte ich mal hochgesetzt, weil ich bei so großen Bildern (das waren dann aber auch 4k Bilder) bei der Vorschau schon Probleme bekommen hatte. Wahrscheinlich wäre es sinnvoll, irgendeine Art von Umwandlung/Kompression durchzuführen. Müsste jemand mal recherchieren, was es da so für Möglichkeiten gibt.

Error-Handling fehlt an der Stelle halt wirklich. Komplett wegnehmen würde ich das Size-Limit nämlich nich, hochsetzen kann man aber natürlich machen.

**Comment by sinnloserName4** [comment]
Size limit ist in den letzten Tagen bei mir auch einmal aufgetreten. Können wir zumindest eine Frontendseitige Fehlerbehandlung einfügen?

**Comment by lehoffma** [comment]
Wird in #205 weitergeführt.
