### ISSUE TITLE
Tour abschließen - löschen-Button ohne Funktion

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#164]
Wenn man User aus einer Tour löschen möchte, funktioniert der Button nicht. Man kann nur über die Checkboxes Teilnehmer entfernen.

**Comment by lehoffma** [comment]
Das Löschen hatte anscheinend immer dann nicht funktioniert, wenn man vorher den zu löschenden Eintrag hinzugefügt/bearbeitet hat. Sollte jetzt gefixt sein.
