### ISSUE TITLE
gleichzeitige API Calls werden nicht immer serialisiert

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#165]
Pia und ich haben die Datenbank gefüllt. Immer wenn wir gleichzeitig einen API Aufruf gemacht haben, war die Ladezeit extrem lang (~20 Sekunden). Einmal ist sogar eine Transaktion gescheitert.

**Comment by sinnloserName4** [comment]
liegt scheinbar nicht unbedingt an den gleichzeitigen aufrufen sondern kommt auch so manchmal vor

**Comment by PiaLamprecht** [comment]
![image](https://user-images.githubusercontent.com/25246294/39210239-65c2f57a-4808-11e8-9798-31f2d96aa3a3.png)

![image](https://user-images.githubusercontent.com/25246294/39210249-6f241c8e-4808-11e8-95a8-e41d90f26c43.png)

![image](https://user-images.githubusercontent.com/25246294/39210264-77ddb1a0-4808-11e8-8b16-c89b96cdeae2.png)

**Comment by lehoffma** [comment]
Hatte auch gerade ne ~10s Ladezeit für n GET-Request einer Addresse. 
Kann mir vorstellen, dass die Datenbank einfach noch hart unoptimiert ist. Haben ja keinerlei Indexe oder so angelegt. So viele Datensätze sind das ja jetzt auch nich, aber bei kleineren Datenmengen ist das ja soweit ich weiß nicht aufgetreten.

Würde ich aber auch erstmal hinten anstellen. Das Backend würde ich sowieso irgendwann gern auf Spring umstellen, weil es vieles einfacher machen würde. Im Backend fehlen nämlich eigentlich noch so viele Sachen, die wir bisher komplett ignoriert haben, wie z.B. Pagination. Da wird im Moment einfach immer alles auf ein mal geladen. Und je mehr Daten wir reinstecken, desto bemerkbarer wird das. Das ganze Sortieren und Filtern von Suchergebnissen usw. müsste dann dementsprechend eigentlich auch ins Backend ausgelagert werden.

**Comment by sinnloserName4** [comment]
gibt es das mit dem pagination zeug überhaupt noch?

**Comment by lehoffma** [comment]
Im Backend ist inzwischen Pagination/Serverseitige filterung komplett implementiert, jap. 
Also vorher hatten wir ja immer einfach alle events geladen und dann in javascript gefiltert, was aber halt schnell unperformant geworden wäre. Jetzt kann man die zu filternde property mit als query parameter übergeben, z.B. kriegt man wenn man /api/event?type=1 aufruft nur Touren zurück. 
Da kann/muss man auch sorting (sortBy=property und direction=asc z.B) und eben auch Pagination (page=x und pageSize=y) parameter mit übergeben. Die API unterstützt auch min und max präfixe für die normalen filter parameter, z.B. minDate oder maxDate.

**Comment by sinnloserName4** [comment]
dann  schließe ich das erstmal
