### ISSUE TITLE
Veranstaltungen - Manuell Personen hinzufügen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#169]
Ich bin Admin und wollte Personen hinzufügen zu einer Veranstaltungen. Leider wurden sie nicht hinzugefügt (Vllt auch weil ich nicht Organizer bin?). Jedoch aber ich auch diesen Fehler bekommen:

![image](https://user-images.githubusercontent.com/25246294/39485123-1fa50202-4d78-11e8-8681-d9ecebc7f477.png)

**Comment by lehoffma** [comment]
Das lag wahrscheinlich daran, dass die Tour keine freien Plätze mehr hatte. Das wurde da aber erst im Backend abgefragt, habs jetzt so implementiert, dass der Button disabled wird, wenn keine Plätze mehr frei sind.
