### ISSUE TITLE
Nicht genug Rechte um "Dein Profil" zu sehen

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#174]
Ich hab nicht genug Rechte mein eigenes Profil zu sehen :(

![image](https://user-images.githubusercontent.com/25246294/43253688-cd5c7746-90c5-11e8-867d-8aebcb100b2b.png)

**Comment by lehoffma** [comment]
Ist gefixt, Profile waren einfach stumpf nur für Mitglieder und höher erlaubt, hab vergessen das eigene Profil extra zu handeln für Gäste.
