### ISSUE TITLE
Bestellung mit Lastschrift nicht möglich 

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#177]
Etwas im Warenkorb und hab versucht es mit Lastschrift zu bezahlen 

![image](https://user-images.githubusercontent.com/25246294/43254652-265a24cc-90c8-11e8-9b7b-ed9d11831350.png)

![image](https://user-images.githubusercontent.com/25246294/43254657-2ba39904-90c8-11e8-9daa-99ed3c7ed7a2.png)

**Comment by PiaLamprecht** [comment]
Mit Überweisung auch nicht möglich 

![image](https://user-images.githubusercontent.com/25246294/43254888-a716bb16-90c8-11e8-9ebb-3f444ee8aa6b.png)

**Comment by PiaLamprecht** [comment]
Bar geht auch nicht

**Comment by lehoffma** [comment]
Ist gefixt, siehe #178
