### ISSUE TITLE
User erstellen führt zu Timeout

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#178]
Wenn ich einen User erstellen möchte, bekomme ich einen Server Timeout 504

![image](https://user-images.githubusercontent.com/6012426/43264481-a15b97f0-90e6-11e8-8c54-f39f2d7dbb90.png)

**Comment by sinnloserName4** [comment]
Alle weiteren Requests werden mit 400 abgebrochen

**Comment by sinnloserName4** [comment]
Trotz allem scheint der 504 Request erfolgreich zu sein. Jedenfalls erscheint der erstellte Member nun in der Liste

**Comment by lehoffma** [comment]
Anscheinend hat jeder Request, der eine Mail zur Folge hat, zu nem Timeout (aber sonst keinem error logging) geführt, weil er die Mail nicht zuende schicken kann und javaMail da n unendlichen timeout hat. 

Habs gefixt, indem ich die dependency versionen aufeinander abgestimmt hab (war vorher 1.6.1 und 1.5.3, is jetzt beides 1.6.1).
