### ISSUE TITLE
EMail-Adresse "wird bereits verwendet" nicht korrekt

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#180]
E-Mail Adresse von Lennard Fricke soll bereits existieren ist in der DB aber nicht vorhanden 
![image](https://user-images.githubusercontent.com/25246294/43276072-dba7dee2-9103-11e8-9e38-f1fff6b244d0.png)

**Comment by sinnloserName4** [comment]
![image](https://user-images.githubusercontent.com/6012426/43276041-c78cb022-9103-11e8-8331-7190a34775ee.png)

**Comment by PiaLamprecht** [comment]
Nachdem ich die E-Mail Adresse noch einmal eingefügt hab ging sie
