### ISSUE TITLE
Adressen werden doppelt in Datenbank erstellt

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#181]
Beim Erstellen eines Users wird die Adresse als gesonderter Request gespeichert. Anscheinend wird sie jedoch zwei Mal geschickt. Das hat im laufenden Betrieb keinerlei Auswirkungen, müllt allerdings die db zu

**Comment by lehoffma** [comment]
Ist gefixt. War mal wieder n falscher Cascade wert (ALL), hab ihn auf REMOVE gesetzt.
