### ISSUE TITLE
Item "öffnen in neuem Tab" gibt 404-Error

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#182]
Detailseiten von Items lassen sich nicht in einem neuen Tab öffnen. Anstatt des richtigen Links kommt nur 404. Könnte mit dem Protokoll zusammenhängen

**Comment by sinnloserName4** [comment]
Passiert bei Chrome 67 bei allen Items. Der Link ist korrekt (siehe Screenshot)

![image](https://user-images.githubusercontent.com/6012426/43311478-df9c992a-918a-11e8-851f-da396e09f820.png)

**Comment by sinnloserName4** [comment]
tritt bei pia in der gleichen browserversion auch auf

**Comment by lehoffma** [comment]
Welchen Account benutzt ihr? Passiert euch das auch wenn ihr den Admin account benutzt? 

Ich kann mir vorstellen, dass das auch mit #187 zusammenhängt, aber bei mir funktioniert das alles sowohl für den admin, als auch für meinen account.
