### ISSUE TITLE
20 von 40 Plätze sind verfügbar

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#184]
Hab die Plätze von 20 Plätze auf 40 erhöht.
Dann steht dort "20 von 40 Plätze sind verfügbar" obwohl es keine Teilnehmer gibt
![image](https://user-images.githubusercontent.com/25246294/43289732-2a5205e0-912c-11e8-8a32-11f945b16e24.png)

**Comment by sinnloserName4** [comment]
dieser Bug hintert mich am Eintragen der Mitfahrer für Schalke in der vergangenen Saison

**Comment by lehoffma** [comment]
Soweit ich das sehe is das nur ein clientseitiger Fehler, weil der gecachete wert nich richtig invalidated wird. Beim Refresh sollten die Werte wieder richtig sein. Fix ich aber noch.

**Comment by lehoffma** [comment]
ist gefixt
