### ISSUE TITLE
Discount für Mitfahrer

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#185]
Wenn Mitglieder weitere Mitfahrer eintragen, dürfen diese keinen Discount bekommen. 

![image](https://user-images.githubusercontent.com/6012426/43290214-b3c60794-912d-11e8-87eb-34d92b9fa5cb.png)

hierbei sollte der zweite also ohne Discount sein

**Comment by lehoffma** [comment]
Ist implementiert. Sowohl für mehrere Items pro Bestellung, als auch für einzelne Bestellungen.
