### ISSUE TITLE
Neues Feld bei Ordered Item: Beschreibung

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#186]
Das Objekt "Ordered Item" soll ein neues Feld "Description" erhalten, in dem weitere Informationen über die Transaktion eingetragen werden können. Dies soll z.B. möglich sein, wenn der Organizer Personen zu einem Event zuordnet, sodass dort klar erkennbar sein kann, dass z.B. ein Mitfahrer ein externer Kumpel o.Ä. ist.

**Comment by lehoffma** [comment]
Ist implementiert. War mir nur noch nicht ganz sicher, was die Permissions angeht. Im Moment hab ich erstmal gesagt, dass alle User mit `funds` Permission >= `read` die Beschreibung sehen können, womit alle User die mindestens Vorstand sind eingeschlossen sind.
