### ISSUE TITLE
Touren sind sichtbar obwohl Rechtestatus nicht ausreicht

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#187]
Ich als Gast kann alle Veranstaltungen für Mitglieder sehen 

![image](https://user-images.githubusercontent.com/25246294/43311271-4002701a-918a-11e8-888a-59c7ca840095.png)

**Comment by lehoffma** [comment]
Da hab ich die authentification logik einfach falsch implementiert (hatte OR statt AND..), ist gefixt.
