### ISSUE TITLE
Image upload sichern

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#205]
Das Hochladen von Bildern sollte gegen falsche Typen und Dateigrößen abgesichert werden

**Comment by lehoffma** [comment]
Das frontend zeigt jetzt einen Fehler an, wenn zu große (> 10MB) oder falsche (d.h. nicht jpg/png) dateien hochgeladen werden und verhindert den Upload. Serverseitig wird der gleiche Check durchgeführt und wirft einen Fehler falls mindestens einer der hochgeladenen parts die einschränkung verletzt.
