### ISSUE TITLE
Zwei gleiche Accounts (mit gleichen Email Adressen) können erstellt werden

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#214]
![image](https://user-images.githubusercontent.com/6012426/48626057-30ae1b80-e9b1-11e8-80b0-305ae9ec5526.png)

**Comment by lehoffma** [comment]
Es existieren bereits Precondition checks im UserServlet, ich habe aber auch noch mal als extra Absicherung den `unique` Wert der JPA Annotation auf `true` gesetzt. 

Edit: (im `develop` Branch)
