### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#23]
Das Datenmodell muss ein Permissions-System beinhalten, welches eine feinere Konfiguration ermöglicht, als es anhand der Clubrollen möglich ist.

## Mögliche Implementation
Jedes ShopObjekt (also Merch/Tour/Party. User und Entries werden einfach stumpf ausgeblendet, wenn die Rolle nicht passt) bekommt eine Liste von UserIds zugewiesen, die dieses Objekt ansehen/anlegen/bearbeiten können.  
Also quasi

```
Event.permissions = {
    read: [0,1,5,7,8],
    write: [0,1]
}
```

Frontendseitig würde dann mit jeder Http Request die UserId mitgeschickt werden (wenn der User nicht bereits aus dem Authentification Token (siehe #22) heraus identifiziert werden kann). Falls die übergebene UserId nicht in im read-Array vorkommt, wird ein 403 Code zurückgeschickt. Falls doch, wird das Event zusammen mit einem Indikator, ob der User denn das Event editieren/modifizieren darf (also ob die ID im write-Array vorkommt) zurückgeschickt.

**Comment by sinnloserName4** [comment]
Dieses Modell kommt nicht hin wenn wir >100 Users haben, bzw sollte es nur eine Erweiterung des angedachten Systems sein. Ich schreibe die Permissionsarchitektur so wie ich sie mir vorgestellt habe ins Wiki, dann können wir das morgen thematisieren

**Comment by sinnloserName4** [comment]
siehe wiki

**Comment by lehoffma** [comment]
Die expected(Read/Write/CheckIn)Roles können jetzt beim Erstellen von Shopitems festgelegt werden. Im Backend sind dazu auch schon einige Änderungen vorgenommen worden, einige Authentication Klassen sind aber noch unvollständig. Im Frontend werden die expectedRole Werte auch weitesgehend beachtet (wenn ich nichts vergessen habe).
