### ISSUE TITLE
Farben als Kombination aus Hex-Wert und Beschreibung speichern

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#24]
Bisher werden die Farben lediglich als String-Wert gespeichert, was es jedoch schwierig macht, diese dynamisch im Frontend zu verwenden (z.B. bei den Suchergebnissen).

Besser wäre sowas wie:

```
merch.colors = [
    {
         hex: "#ffffff",
         name: "Weiss"
    },
    ...
]
```

**Comment by sinnloserName4** [comment]
werden vom backend angenommen, in die datenbank geschrieben und auch wieder zurückgegeben. Einziges Problem liegt in #28
