### ISSUE TITLE
Anpassungen an Event-Routen Datenmodell

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#25]
Die beiden Event-Properties (meetingPoint + destination) sollen zu einem Routen-Objekt zusammengefasst werden. Eventuell könnte man sogar ein Array daraus machen, um Zwischenziele zu ermöglichen?

Des Weiteren sollten die Routen-Stoppunkte zusätzlich jeweils die Längen- und Breitengrade mitspeichern, da diese für die Darstellung der Touren-Karten benötigt werden.

**Comment by sinnloserName4** [comment]
Latitude und longitude hinzugefügt.

**Comment by sinnloserName4** [comment]
Das Backend nimmt die Routendaten wie die Adressdaten des Users als JsonArray aus IDs entgegen. Hierbei müssen die Adressen vorher schon an den Server geschickt werden.
