### ISSUE TITLE
User Object Updaten

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#26]
neue Properties:

Geschlecht
Eintrittsdatum
Wölfeclubmitglied
Dauerkarteninhaber

**Comment by lehoffma** [comment]
Der Konstruktor wurde um das hier erweitert.

```javascript

public readonly gender: Gender,
public readonly joinDate: Date,
public readonly isWoelfeClubMember: boolean,
public readonly hasSeasonTicket: boolean,

```

Gender ist dabei definiert als

```javascript
enum Gender {
	FEMALE,
	MALE,
	OTHER
}
```

Ich würde jetzt noch die Permissions raus schmeißen, da die ja wahrscheinlich mit dem neuen Permissions System (#23) nicht mehr gebraucht werden, oder?
