### ISSUE TITLE
Address api implementieren

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#30]
Note: bitte im Code überall `Address` (mit doppel-D) verwenden.

- [x] GET

- [x] POST

- [x] PUT

- [x] DELETE

**Comment by lehoffma** [comment]
Ist frontendseitig implementiert.

Zum Wiki-Eintrag: Kanns sein dass das einfach copy-paste von der user-api is? 😁 Außerdem wurde da Address nur mit einem D geschrieben :D

**Comment by sinnloserName4** [comment]
ja ist copy paste, ist ja auch nicht großartig etwas anderes zu tun. Ist im Wiki geändert, nur noch die deutschen Vorkommen haben ein d

**Comment by sinnloserName4** [comment]
implementiert
