### ISSUE TITLE
Stock API implementieren

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#31]
- [x] GET

- [x] POST

- [x] PUT

- [x] DELETE

**Comment by lehoffma** [comment]
> Methode: GET
>
> Url: /api/stock
>
> Params 'id': Stock-ID (optional) 'searchTerm': Sucheingabe (optional, default='')
> 
> Returns on success: HttpStatusCode 200, Body: { 'stock': Array mit allem stock, das auf den searchTerm matcht }

Heißt das, dass jedes Stock item ne eigene ID bekommt? Oder jede Stock item liste? Ich würde sonst sagen dass man da am besten die EventId übergibt, oder is das dann doof wenn man nen bestand außerhalb eines events haben möchte?

**Comment by sinnloserName4** [comment]
wir können beides machen. Es wird aber vermutlich ähnlich wie bei den Kosten sein, dass auch die anderen Stock sachen zu irgendeinem fake eintrag gehören. 

Habe den parameter ergänzt

**Comment by sinnloserName4** [comment]
die anderen funktionen implementieren und aus Event löschen

**Comment by PiaLamprecht** [comment]
ist implementiert. Post und Put gehen davon aus, dass immer eine Zeile übergeben wird. Für eine ganze Tabelle muss der Aufruf wiederholt werden.

**Comment by PiaLamprecht** [comment]
In Event bleiben sie vorerst drin, bis das Frontend umgestellt wurde.

**Comment by lehoffma** [comment]
Ist frontendseitig auch umgestellt.
