### ISSUE TITLE
Kommentarfunktion

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#34]
Jede Tour, Party und Merchandise Detailseite sollte die Möglichkeit bieten, Kommentare zu hinterlassen.

Ich würde dafür folgende Datenstruktur vorschlagen

```java
class Comment{
   public int eventId;
   public int id;   //globale unique ID
   public Date timeStamp;   //muss jetzt unbedingt nich 'Date' sein, aber halt nen Datumstyp
   public int authorId;
   public String text;
}


```

Damit müsste zumindest der grundlegende Teil abgedeckt sein. 

Ich würde dann auch eine eigene Comments API vorschlagen, die aus folgenden funktionen besteht

- **GET**: `getCommentsOfEvent(int eventId)` => `{comments: Comment[]}`
- **POST**: `addCommentToEvent(int eventId, Comment comment)` => `void?`
- **PUT**: `editCommentOfEvent(int eventId, Comment comment)` => `void?`
- **DELETE**: `deleteCommentOfEvent(int eventId, int commentId)` => `void?`

Eine Erweiterungsmöglichkeit wäre, dem Comment-Objekt ein Parent-attribute (sowas wie `public int parentId`) oder ein children-attribute (`public List<Integer> children`) hinzuzufügen, womit wir dann richtige comment-threads haben könnten (wie bei facebook oder so).

Weitere Ideen/Verbesserungsvorschläge?

**Comment by lehoffma** [comment]
Soweit fertig, Add/Delete Funktionalität wurde aber noch nicht getestet, da dafür ein Backend benötigt wird

**Comment by sinnloserName4** [comment]
Gibt es jetzt ne ParentID?

**Comment by sinnloserName4** [comment]
API ist prototypisch implementiert. Änderung am Datenbankschema kann neuerstellen des Schemas in MySQL notwendig machen

**Comment by lehoffma** [comment]
Nee, gibt keine ParentId

**Comment by sinnloserName4** [comment]
ToDo: Hierarchische Kommentare im Backend mithilfe von Children IDs

**Comment by PiaLamprecht** [comment]
Fehler: wenn man einen Kommentar macht, dann steht dort "in 2 Stunden" auch wenn es erst 10 Sekunden her ist
