### ISSUE TITLE
"Weiterleitung" der Angular-Routen

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#37]
### Schritte zum Reproduzieren

1. Falls Bundle noch nicht vorhanden: `npm build` ausführen
1. Tomcat starten
2. Im Frontend von der Startseite wegnavigieren
3. Den Browser aktualisieren

### Gewünschtes Ergebnis

Die Seite, zu der man hin navigiert hat, wird aktualisiert.

### Wirkliches Ergebnis

Es wird ein 404-Errorcode zurückgegeben.

### How to (probably) fix
Wenn es sich ähnlich wie bei Spring Boot verhält (is ja eigentlich auf den gleichen Technologien aufgebaut), muss man dafür nur ein Servlet erstellen, welches die Routen, die von Angular verwendet werden (z.b. "/calendar"), matcht und weiter zur Index.html forwarded.

**Comment by sinnloserName4** [comment]
welche routen müssen wir denn alle weiterleiten?

**Comment by lehoffma** [comment]
Aus der app.routes datei kopiert: 

- "search"
- ":itemType/:id/edit"
- ":itemType/create"

- ":itemType/:eventId/costs"
- ":itemType/:eventId/costs/:id/edit"
- ":itemType/:eventId/costs/create"


- "tours"
- "tours/:id"
- "tours/:id/participants"

- "partys"
- "partys/:id"
- "partys/:id/participants"

- "merch"
- "merch/:id"

- "calendar"

- "members"
- "members/:id"
- "members/:id/edit"
- "members/:id/address"
- "address"


- "login"
- "signup"
- "signup/:step"
- "cart"
- "checkout"

- "my-events"
- "order-history"
	
- "management/costs"
- "management/stock"
- "management/stock/merch"
	
- "settings"
- "impressum"
- "not-allowed"
- "redirect"
- "page-not-found"


die sachen mit : davor sind path parameter
