### ISSUE TITLE
keine Weiterleitung nach Eingabe einer Adresse bei der Registrierung

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#38]
Workflow zum Reproduzieren des Fehlers:

- neu registrieren
- Email und Passwort angeben
- persönliche Daten angeben
- "neue Adresse hinzufügen" wählen
- Adresse eingeben und auf speichern drücken

Gewünschtes Ergebnis:

Adresse wird in Datenbank abgespeichert und die ID im User gespeichert. Anschließend wird man zurück zur "User erstellen"-Ansicht geleitet.

Wirkliches Ergebnis:

Adresse wird in Datenbank abgespeichert. Keine Weiterleitung

**Comment by lehoffma** [comment]
Weiterleitung is jetzt drin
