### ISSUE TITLE
Adressen werden mehrfach angelegt

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#39]
Workflow zum Reproduzieren des Fehlers:

- neu registrieren
- Email und Passwort angeben
- persönliche Daten angeben
- "neue Adresse hinzufügen" wählen
- bereits vergebene Adresse eingeben und auf speichern drücken

Gewünschtes Ergebnis:

Adresse wird mit Inhalt der Datenbank verglichen und der bereits vorhandene Eintrag zurückgegeben

Wirkliches Ergebnis:

Adresse wird in Datenbank abgespeichert. Doppelte Einträge

**Comment by lehoffma** [comment]
wurde in [bug fixes + last commit before presentation](https://github.com/lehoffma/memo/commit/1de6b82176c8f4c1642d5aa001eb1ae38a358dde) bereits gefixt, addressen wurden im setter zur bestehenden liste hinzugefügt statt überschrieben.
