### ISSUE TITLE
Fehlende Werte bei der User Erstellung

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#40]
Manche Werte werden nicht an das Backend gesendet, teilweise auch unzuverlässig.
u.a. folgende values:

- [x] Adresse (siehe #38 )
- [x]  Birthday
- [x] manchmal Email & Password
- [x] Dauerkarte und Wölfeclub ist immer false
- [x] Gender ist immer "Keine Angabe" | besser wäre (m,w,null)

**Comment by lehoffma** [comment]
Lag hauptsächlich an der Address-Geschichte, da nach der Weiterleitung die Daten einfach verloren gegangen waren. Wird jetzt alles in nem extra Service gespeichert, sollte also jetzt funktionieren.
