### ISSUE TITLE
Einloggen nicht möglich trotz richtiger login daten

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#44]
Das Backend gibt ein 202 Accepted zurück und trotzdem meldet das Frontend, dass die Daten falsch sind.

**Comment by lehoffma** [comment]
Der JSON vom Backend ist falsch formatiert. Die Response sieht im Moment so aus

`{ 'id': 1, 'auth_token': null }`

sollte aber eigentlich so aussehen:

`{ "id": 1, "auth_token": null }`
