### ISSUE TITLE
Fehlende/Unpassende JSON felder in User API Responses

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#46]
1. Addresses sollte mit zwei D geschrieben werden
2. der Birthday ist immer der 1. Januar 1970, egal was beim signup gesendet wurde.
3. Die ClubRole ist komplett leer. Falls dem User keine Rolle zugewiesen wurde, sollte die Rolle "0" oder "None" sein
4. Ich finde die Bank accounts sollte man auch nich unbedingt bei jedem GET mitschicken, ich würde das eher über nen seperaten API aufruf regeln

**Comment by sinnloserName4** [comment]
Addresses habe ich keinen fehler gefunden. Hast du das schon gemacht?

Birthday hast du ja gefixt

Clubrole ist gefixt

Bank accounts sehe ich ähnlich aber deshalb bekommt man ja auch nur die id zurück

**Comment by sinnloserName4** [comment]
Addresses fehler gefunden

BankAccounts würde ich später angehen
