### ISSUE TITLE
ImageUpload Servlet/API

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#48]
Da ein hochgeladenes Bild im FormData/MultipartFile Format vorliegt und dementsprechend nicht in einem "rutsch" mit den anderen JSON daten in den POST request geschickt werden kann (HTTP unterstützt mehrere Content-Types innerhalb eines Requests anscheinend nicht so gut), sollten wir einen seperaten ImageServlet anlegen. 

Für das Backend sieht das eigentlich ganz gut aus aufn ersten blick:  
https://stackoverflow.com/questions/2422468/how-to-upload-files-to-server-using-jsp-servlet

**Comment by lehoffma** [comment]
Beim Modifizieren/Hinzufügen und beim Signup sollte jetzt bevor den entsprechenden submit POST/PUT requests auch ein POST-request an /api/image getätigt werden (multipart/form-data)

**Comment by sinnloserName4** [comment]
mögliche Lösung: https://stackoverflow.com/questions/24890675/file-upload-using-rest-api-in-java

**Comment by lehoffma** [comment]
Ist seit [diesem Commit](https://github.com/lehoffma/memo/commit/f3baf1817e001b3e458c06fb312b7de34e2e9953) fertig implementiert.
