### ISSUE TITLE
Order Servlet/API implementieren

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#49]
Im Moment gibt es noch keine richtige Möglichkeit dem Backend zu sagen, dass gerade etwas bestellt wurde. Und andersrum gibt es auch keine "getOrdersByUserId" Funktion, die wir für den "Deine Bestellungen" Menüpunkt wahrscheinlich brauchen werden.

Ich würde ne eigene API vorschlagen. Dafür müsste dementsprechend auch die Datenbank angepasst werden, da die Bestellungen im Moment soweit ich weiß noch nicht enthalten sind.

Vielleicht irgendwie sowas?

```java

@Entity
@Table(name="ORDERS")
public class Order implements Serializable {

    @Expose
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    @Expose
    @Column(nullable=false)
    private Integer userId //also als fremdschlüssel oder so

    @Expose
    @Column(nullable=false)
    private PaymentMethod method; //enum von den möglichen Payment methoden

    @Expose
    @Column(nullable=false)
    private Map<Event, Integer> orderedItems; //der Integer soll dabei die Anzahl sein.
// Aber vllt macht ne extra Klasse (und dann ne Liste davon statt ner Map) doch eher Sinn,
// man muss ja auch die ausgewählte Größe/Farbe irgendwie speichern 

   //...get/set/equals blabla
}
```

die API könnte dann ungefähr so aussehen?

Methode: GET
URL: /api/order   
mögliche queryParameter: 
- orderId
- userId: um alle Orders eines Users zu bekommen

Methode: POST
URL: /api/order
mögliche queryParameter:
- paymentMethod: siehe oben
- cartContent: Array von 
```
{
    event: <Event>
    amount: <number>
    options: {
        color: <color>
        size: <string>
    }
}
```
- userId
- data: Bezahldaten die eingegeben wurden?

**Comment by sinnloserName4** [comment]
Bei der Überarbeitung der Bestelllogik hat sich folgendes geändert: 

- Eine Bestellung hat einen Timestamp (wird erst im Backend vergeben)
- die OrderStati jedes OrderedItem sind folgende #52
- Amount funktioniert für OrderedItem nicht (z.B. bei Updates, wobei ein Artikel von 2 gleichen geändert wird). Daher sollten auch zwei gleiche Artikel immer zwei OrderedItems sein
-OrderedItem hat neben den Color und Size Attributes für Merch auch noch die Boolean Attribute "isDriver" und "needsTicket" für Touren

**Comment by sinnloserName4** [comment]
ToDo: debug
