### ISSUE TITLE
MeinAccount ist leer

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#50]
Wenn man angemeldet ist und dann auf "MeinenAccount" geht sollte man seine eigenen Daten ändern. Dort werden jedoch keine Daten angezeigt. 

Schritt für Schritt:

1. Account erstellen
2. mit diesem Account sich anmelden
3. auf "Dein Account" gehen

Gewünschtes Ergebnis: bereits gefüllt Felder, die geändert werden können

Wirkliches Ergebnis: alle Felder sind leer

**Comment by lehoffma** [comment]
sollte inzwischen gehen.

wenn nich hab ichs einfach noch nich gepusht, würde ich dann nach der arbeit machen
