### ISSUE TITLE
Email Funktionalität

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#60]
der Shop sendet mails

**Comment by lehoffma** [comment]
Mögliche Mails:

- [ ] Registrierung
- [ ] Passwort vergessen
- [ ] Bestellbestätigung
- [ ] Verantwortliche User Benachrichtigung
- [ ] Tourdaten ändern sich

**Comment by PiaLamprecht** [comment]
Tourdaten Aktuallisierung: 

![image](https://user-images.githubusercontent.com/25246294/38455099-21bec194-3a73-11e8-83f8-02b5d0f1912f.png)

könnt es aber auch ganz anders machen. Stell dir html in drive

**Comment by PiaLamprecht** [comment]
Html:
- [ ] Registrierung 
- [ ] Password vergessen
- [ ] Mitglied der MW
- [ ] Bestellbestätigung
- [ ] Verantwortlicher User
- [ ] Tourdatenaktuallisierung

**Comment by lehoffma** [comment]
Mails sind soweit alle implementiert, aber noch null getestet. Damit nichts anderes dadurch kaputt geht, wird die Ausführung im Moment erstmal verhindert. 
Wenn ihr sie mal ausprobieren wollt, müsst ihr nur im `CommunicationManager` den If-Block in `getTransmitters` auskommentieren/entfernen. Ich glaube bei manchen Anwendungsfällen müssen ein paar Platzhalter im Html Template angepasst werden. Die Passwort vergessen Email müsste eigentlich sogar schon funktionieren :D

**Comment by lehoffma** [comment]
Hab's jetzt mal n bisschen getestet/Fehler gefixt. Die "Itemdaten ändern sich" Mail funktioniert noch nich so ganz, weil getOrders() irgendwie immer ne leere Liste zurückliefert. Aber Registrierung, Passwort vergessen, Bestellbestätigung und Verantwortliche User Benachrichtigung funktionieren alle.

**Comment by lehoffma** [comment]
Fehlende Mails:

- [ ] Überweisung
- [ ] Lastschrift

**Comment by PiaLamprecht** [comment]
**Lastschrift** für den Kassenwart der Meilenwölfe:

![image](https://user-images.githubusercontent.com/25246294/38554156-c49a2750-3cc1-11e8-94fd-5e782b3bc967.png)

**Lastschrift** an den Käufer:

![image](https://user-images.githubusercontent.com/25246294/38554359-97e1a7fa-3cc2-11e8-9cf0-b54fab08ad4c.png)

Für die Überweisung habe ich ebenfalls zwei E-Mail vorbereitet. Siehe Drive 

Für die Statusänderung habe ich ebenfalls eine E-Mail gebaut.

**Comment by lehoffma** [comment]
Update: Lastschrift/Überweisung/StatusChangeRequest sind implementiert und funktionieren für den Kunden zumindest. Für den Admin hab ich's noch nicht getestet. Könntet ihr das noch mal machen?

**Comment by PiaLamprecht** [comment]
Admin läuft
