### ISSUE TITLE
Verantwortlichen Info bei Events

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#61]
Im Shop Item sollte es Informationen über Verantwortliche geben inkl. Kontaktinfos

**Comment by lehoffma** [comment]
Die Anzeige der Verantwortlichen ist frontendseitig prototypisch implementiert. 

Es fehlen noch:
- Hinzufügen von verantwortlichen beim Erstellen/Modifizieren des Items
- Die Verbindung zum Backend (@sinnloserName4 : die Verantwortlichen sind einfach die authors eines shopitems, oder?)
