### ISSUE TITLE
OrderAPI-POST-Request: OrderedItems bekommen keine orderId zugewiesen

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#65]
Die in der Datenbank angelegten OrderItems kriegen beim Abschließen einer Bestellung keine OrderId zugewiesen (bzw sie ist null), weshalb die OrderedItems bei den GET-Requests immer leer sind.

**Comment by sinnloserName4** [comment]
sollte nicht mehr auftreten

**Comment by PiaLamprecht** [comment]
funktioniert noch nicht

**Comment by sinnloserName4** [comment]
sollte funktionieren

**Comment by PiaLamprecht** [comment]
jetzt funktioniert es: 
- alle getätigten Bestellungen werden in "Deine Bestellungen" angezeigt.
- leider werden gleich Artikel mehrfach angezeigt und nicht etwa dafür die Anzahl angzeigt - sollten wir vllt besprechen

was nicht funktioniert:

- [ ]  Deine Events wird kein Event angezeigt, auch nicht die von mir erstellten

- [ ] In meinem Profil steht, dass ich an keiner Tour teilgenommen hab

**Comment by lehoffma** [comment]
Die von dir erstellten Events werden angezeigt, sobald #72 gefixt ist. Die Touren in deinem Profil sind jetzt wieder da. Die getätigten Bestellungen sollten jetzt auch korrekt dargestellt werden.
