### ISSUE TITLE
Fehler beim Merchandise

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#66]
Bei jedem Merchandise Artikel wird Lager immer auf -1 gesetzt.
Wahrscheinlich müsste Lager eher die Anzahl aller Artikel sein

**Comment by lehoffma** [comment]
wurde [hier](https://github.com/lehoffma/memo/commit/49178dc7a070f43d23c0f8301696a69ed3e8df82) gefixt
