### ISSUE TITLE
Fehler bei Tour

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#67]
- [x] Freie Plätze ist immer -1 müsste denke ich aber capacity - teilnehmende sein

- [x] Meilen sind immer -1, da Meilen beim Erstellen einer Tour nicht angegeben werden können

**Comment by lehoffma** [comment]
Teil 1 wurde [hier](https://github.com/lehoffma/memo/commit/49178dc7a070f43d23c0f8301696a69ed3e8df82) gefixt.

Bei Teil 2: Sollte man die meilen direkt eingeben oder eher automatisch berechnen lassen? Und sollen die Meilen vor der Tour festgelegt werden oder nach der Tour?

**Comment by PiaLamprecht** [comment]
Teil 2:
Ich bin dafür, dass man die Meilen beim Erstellen eingeben sollte.
Pro:
- man kann die Meilen so runden wie man möchte
- man muss noch kein entgültigen Start und Zielort angeben 
Contra:
- die Meilen könnten falsch berechnet werden
- mehr Mühe, da man sie selbst berechnen muss
- Was passiert wenn eine andere Route gewählt wird?

@sinnloserName4  wie siehst du das?

**Comment by sinnloserName4** [comment]
würde es im ersten Versuch beim erstellen angeben. Über automatisierungen kann man ja später noch sprechen

**Comment by lehoffma** [comment]
Wird im Moment automatisch berechnet und dann auch ans Backend übergeben. Der Wert wird allerdings beim Erstellen nicht direkt angezeigt, man kann ihn also nur bei der fertigen Tour sehen bisher.
