### ISSUE TITLE
Löschen vom Bestand

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#68]
wenn der Bestand bearbeiten werden soll:
- auf den Bestand gehen und eine einzelne Farbe/größe wählen um sie zu bearbeiten
- die Anzahl verändern -> hat keine Auswirkung auf die Anzahl
- die Farbe/Größe löschen -> hat auch keine Auswirkungen

Also:

- [x] Anzahl ändern funktioniert nicht

- [x] Löschen von einzelnen Farben/Größen funktioniert nicht

**Comment by lehoffma** [comment]
sollte damit zusammenhängen: #57

**Comment by lehoffma** [comment]
wurde [hier](https://github.com/lehoffma/memo/commit/bb58e5f679cc48e781d7dc21a3795e0bfcf212c6) gefixt
