### ISSUE TITLE
Fehler bei der Registrierung

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#69]
Bei der Registrierung wird die Adresse, die man angibt, wenn man die Lastschrift angibt, nicht gespeichert

**Comment by lehoffma** [comment]
Soll die Addresse dann einfach zu dem Address-Array vom User dazugefügt werden? Oder gibts da irgendwo n anderen ort wo die gespeichert wird=

**Comment by PiaLamprecht** [comment]
einfach zum Address-Array hinzufügen
