### ISSUE TITLE
Fehler beim "Tour erstellen"

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#70]
Wenn man auf Home ist und keine Touren vorhanden sind, steht dort "Tour erstellen", wenn man darauf klickt gibt es einen Fehler

**Comment by lehoffma** [comment]
wurde [hier](https://github.com/lehoffma/memo/commit/e0c50aceed88cd6847c259ac8ad5ccb4583b8a56) gefixt
