### ISSUE TITLE
Fehler bei "dein Profil"

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#71]
Wenn man auf der mobilen Version ist und auf "deinProfil" geht und danach das Menü an der Seite öffnet, ist das Menü hinter dem Profil. Also das Profil ist im Vordergrund und so kann man das Menü nicht bedienen.

**Comment by lehoffma** [comment]
wurde [hier](https://github.com/lehoffma/memo/commit/e0c50aceed88cd6847c259ac8ad5ccb4583b8a56) gefixt
