### ISSUE TITLE
Fehler bei "deine Bestellungen"

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#73]
- ich habe eine Tour bestellt
- dann klicke ich auf "deine Bestellungen"
- dann wird angezeigt, dass ich eine Bestellung vom 21.09 habe, sie bar bezahlt wurde, aber dort steht 0 Euro und dort fehlt was ich gekauft habe

**Comment by lehoffma** [comment]
sollte damit zusammenhängen: #65
