### ISSUE TITLE
Kostenübersicht Bearbeitung

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#76]
Wenn es eine Menge an Kosten gibt und einen Kostenpunkt bearbeiten möchte, dann wird automatisch immer der erste Eintrag bearbeitet und nicht, der Eintrag den man bearbeiten möchte.

**Comment by PiaLamprecht** [comment]
Löschen funktioniert

**Comment by lehoffma** [comment]
Kanns nich wirklich reproduzieren. Hab da nur ein Caching Problem entdeckt, was in meinem nächsten Commit gefixt wird. Da wurden aber nur manchmal im Frontend alte Daten angezeigt, d.h. wenn du was editiert hast, hatte es sich da nich unbedingt geupdated. An sich funktioniert das editieren bei mir aber.

**Comment by PiaLamprecht** [comment]
bei funktioniert jetzt auch alles 👍
