### ISSUE TITLE
Mitgliederliste - Mitglieder zufügen - Problem

### ISSUE THREAD

**Issue by PiaLamprecht** [lehoffma/memo#79]
- [ ] Wenn man Mitglieder hinzufügt und ihnen eine Rolle gibt ist das Symbol immer Admin (Stern) (in der Datenbank wird die Rolle richtig gespeichert)

![image](https://user-images.githubusercontent.com/25246294/31056688-0bdafb26-a6d6-11e7-8d66-8d700d623c4d.png)

- [x]  Wenn ich ein Mitglied erstelle wird das Passwort nicht in die Datenbank gespeichert

- [x]  Wenn ich ein Mitglied hinzufüge mit einer Adresse - geht das Adressfenster nicht zu - danach sind alle bereits eingegebene Daten des Users weg

**Comment by PiaLamprecht** [comment]
hab jetzt gemerkt, dass er die Adresse mir zugeordnet hat und nicht dem Mitglied, dass die Adresse haben sollte

**Comment by lehoffma** [comment]
>  Wenn man Mitglieder hinzufügt und ihnen eine Rolle gibt ist das Symbol immer Admin (Stern) (in der Datenbank wird die Rolle richtig gespeichert)
Das war bisher Absicht, da wir am Anfang nen Admin Account brauchten. Man kann ja keine Rollen vergeben wenn man nich selber Admin/zumindest was anderes als "nichts" is. Die Stelle ist aber mit "todo remove demo" gekennzeichnet

Der Rest sollte gefixt sein.

Allerdings gibts noch nen bug, wenn man ne email eingibt die bereits existiert. An dem setz ich mich aber als nächstes dran.

**Comment by sinnloserName4** [comment]
Das sollte im Frontend aber funktionieren, es gibt nur nen demo eintrag im Backend, dass ein neu registrierter dude immer admin ist

**Comment by sinnloserName4** [comment]
wird weiter in #131 betrachtet, deshalb close
