### ISSUE TITLE
Bilder löschen

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#87]

**Comment by lehoffma** [comment]
Frontend fehlt noch

**Comment by lehoffma** [comment]
Bilder können jetzt auch im Frontend gelöscht werden (seit [diesem Commit](https://github.com/lehoffma/memo/commit/c78f357bdac79a6f9c76656e2156181b98140f5c)). Dafür muss in der Modify-X Seite des Shopitems einfach der Eintrag aus der Tabelle gelöscht und die Änderungen gespeichert werden.
