### ISSUE TITLE
Profillink in Participants

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#92]

**Comment by sinnloserName4** [comment]
whatsapp integration?

**Comment by lehoffma** [comment]
https://faq.whatsapp.com/en/android/26000030/?category=5245251

**Comment by lehoffma** [comment]
Wurde [hier](https://github.com/lehoffma/memo/commit/d91e6b31143743781d04dfd1fe37cc5945ecf1d0) implementiert.
