### ISSUE TITLE
Prozess für Fahrten abbilden

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#93]
1. Fahrt anlegen
2. Member melden sich an 
3. Vor der Tour: Verantwortlichen benennen
4. Fahrer und Bezahlung prüfen
5. Erinnerungsnachricht mit Treffpunkt schicken
6. Treffpunkt: Anwesenheit checken und Fahrer eintragen
7. Hinfahrt
8. Parkticket als kosten hinzufügen (Kameraintegration)
9. übrige Tickets verkaufen
10. Gruppenfoto hochladen
11. Rückfahrt
12. Tankquittung hochladen
13. Ankommen
14. Berichtverantwortlichen setzen
15. Bericht hochladen
16. Tour abschließen

ToDo:

- #61 
- Fahrer und Bezahlung prüfen (häkchen setzen und entfernen)
- Kameraintegration
- Bilder hochladen für kosten
- Abschlussbildschirm (Liste zum Abhaken, Gruppenbild, Berichtverantwortlicher)
- DB Struktur für Gruppenfoto

**Comment by lehoffma** [comment]
Kameraintegration ist bereits implementiert, da der bereits vorhandene html file-input (zumindest auf android) einem auch die Kamera als Input-Möglichkeit anbietet.

**Comment by lehoffma** [comment]
Ist jetzt alles implementiert. (Hat ja auch nur noch das Bilder hochladen für Kosten gefehlt)
