### ISSUE TITLE
Conditions für Discounts

### ISSUE THREAD

**Issue by sinnloserName4** [lehoffma/memo#96]
Discounts werden unter gewissen Umständen gewährt.

Folgende Conditions  für User sind möglich:

- [x] User-id Liste   
- [x] Birthday (Altersprüfung)
- [x] Join Date
- [x] club Role
- [x] isWölfeClubMember
- [x] hasSeasonTicket
- [x] isStudent

Folgende Conditions für Items sind möglich:

- [x] Item-Id Liste
- [x] Datum (von bis)
- [x] Preis (min - max)
- [x] type
- [x] miles (min - max)

wenn keine Restriktionen aktiv sind, gelten Discounts für alle.

Nicht aktive Restriktionen sind in der Datenbank null und werden nicht serialisiert
Restriktionen sind ein Objekt innerhalb der Discount-API.

**Comment by lehoffma** [comment]
Die Conditions sind alle als Properties der DiscountEntity implementiert, um die SQL-Abfragen zu vereinfachen/performant zu halten. Weitere Discountdiskussionen würde ich in #95 weiterführen, hier ist sonst alles doppelt.
