### ISSUE TITLE
Verfügbare Tickets updaten nicht nach Bestellen von Tickets

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#98]
### Schritte zum reproduzieren:

1. Mindestens 1 Ticket für eine Party oder Fahrt in den Warenkorb tun (Merch betrifft dieses Problem nicht)
2. Bestelldetails ausfüllen und abschicken

### Was passiert
Die Anzahl verfügbarer Plätze bzw. Tickets bleibt immer gleich.

### Was passieren sollte: 
Auf der Detailseite der Fahrt bzw. der Party sollte sich die Anzahl verfügbarer Plätze nach jeder Bestellung updaten. 

### Lösungsmöglichkeiten
Im Moment wird im Frontend einfach die capacity des Shopitems verwendet, um die Anzahl der Tickets zu kontrollieren. Wollen wir die capacity updaten, sobald eine Bestellung betätigt wird oder sollen stattdessen die participants im Frontend requested werden und die maximale Ticketanzahl dann anhand der Menge an Mitfahrern berechnet werden?

**Comment by sinnloserName4** [comment]
Das Wort "capacity" sagt eigentlich, dass wir es nicht ändern sollten. Letztlich brauchen wir sowohl die Gesamtticketmenge als auch die "open seats". Welches wir davon errechnen ist letztlich egal. Wie würdest du es machen?

**Comment by lehoffma** [comment]
Dann würde ich einfach die open seats anhand der Participants berechnen lassen.

**Comment by lehoffma** [comment]
Für Touren und Partys funktioniert das jetzt soweit, für Merch is es aber noch nicht implementiert (die Verknüpfung mit dem Stock und so is doch n bisschen aufwendiger als gedacht)

**Comment by lehoffma** [comment]
Funktioniert jetzt auch für Merch.
