### ISSUE TITLE
Preis geht ins negative wenn Preis < Discount

### ISSUE THREAD

**Issue by lehoffma** [lehoffma/memo#99]
### Schritte zum reproduzieren

1. Shopitem mit einem Preis < 5€ erstellen
2. Im eingeloggten Zustand zur Detailseite des Items navigieren

### Was passiert
Der Preis wird einfach stumpf um 5 € verringert, was bei Preisen < 5€ zu negativen Preisen und verbuggten Prozentwerten führt. 

### Was passieren sollte
Das weiß ich in dem Fall nicht so genau (weshalb ich das Issue auch aufgemacht habe). Soll der Preis bis auf 0€ runter und der restliche Discount wird ignoriert? Oder soll es lieber einen anderen Mindestwert geben?

**Comment by sinnloserName4** [comment]
Der Preis sollte in diesem Fall 0€ sein. Also priceMember = max( 0 , price - 5 ). Dabei müsste dann auch die Prozentanzeige angepasst werden

**Comment by lehoffma** [comment]
Ist in der Anzeige auf den Detailsseiten erstmal implementiert. Im Warenkorb/Checkout fehlt es noch, aber da sind die Discounts generell noch nicht drin, deshalb close ich das Issue hier mal (das passt dann eher zu #95 oder nem neuen Issue find ich).
